jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(e,a,c,b,d){return jQuery.easing[jQuery.easing.def](e,a,c,b,d)},easeInQuad:function(e,a,c,b,d){return b*(a/=d)*a+c},easeOutQuad:function(e,a,c,b,d){return-b*(a/=d)*(a-2)+c},easeInOutQuad:function(e,a,c,b,d){return 1>(a/=d/2)?b/2*a*a+c:-b/2*(--a*(a-2)-1)+c},easeInCubic:function(e,a,c,b,d){return b*(a/=d)*a*a+c},easeOutCubic:function(e,a,c,b,d){return b*((a=a/d-1)*a*a+1)+c},easeInOutCubic:function(e,a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a+c:
b/2*((a-=2)*a*a+2)+c},easeInQuart:function(e,a,c,b,d){return b*(a/=d)*a*a*a+c},easeOutQuart:function(e,a,c,b,d){return-b*((a=a/d-1)*a*a*a-1)+c},easeInOutQuart:function(e,a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a*a+c:-b/2*((a-=2)*a*a*a-2)+c},easeInQuint:function(e,a,c,b,d){return b*(a/=d)*a*a*a*a+c},easeOutQuint:function(e,a,c,b,d){return b*((a=a/d-1)*a*a*a*a+1)+c},easeInOutQuint:function(e,a,c,b,d){return 1>(a/=d/2)?b/2*a*a*a*a*a+c:b/2*((a-=2)*a*a*a*a+2)+c},easeInSine:function(e,a,c,b,d){return-b*Math.cos(a/
d*(Math.PI/2))+b+c},easeOutSine:function(e,a,c,b,d){return b*Math.sin(a/d*(Math.PI/2))+c},easeInOutSine:function(e,a,c,b,d){return-b/2*(Math.cos(Math.PI*a/d)-1)+c},easeInExpo:function(e,a,c,b,d){return 0==a?c:b*Math.pow(2,10*(a/d-1))+c},easeOutExpo:function(e,a,c,b,d){return a==d?c+b:b*(-Math.pow(2,-10*a/d)+1)+c},easeInOutExpo:function(e,a,c,b,d){return 0==a?c:a==d?c+b:1>(a/=d/2)?b/2*Math.pow(2,10*(a-1))+c:b/2*(-Math.pow(2,-10*--a)+2)+c},easeInCirc:function(e,a,c,b,d){return-b*(Math.sqrt(1-(a/=d)*
a)-1)+c},easeOutCirc:function(e,a,c,b,d){return b*Math.sqrt(1-(a=a/d-1)*a)+c},easeInOutCirc:function(e,a,c,b,d){return 1>(a/=d/2)?-b/2*(Math.sqrt(1-a*a)-1)+c:b/2*(Math.sqrt(1-(a-=2)*a)+1)+c},easeInElastic:function(e,a,c,b,d){e=1.70158;var g=0,l=b;if(0==a)return c;if(1==(a/=d))return c+b;g||(g=.3*d);l<Math.abs(b)?(l=b,e=g/4):e=g/(2*Math.PI)*Math.asin(b/l);return-(l*Math.pow(2,10*--a)*Math.sin(2*(a*d-e)*Math.PI/g))+c},easeOutElastic:function(e,a,c,b,d){e=1.70158;var g=0,l=b;if(0==a)return c;if(1==(a/=
d))return c+b;g||(g=.3*d);l<Math.abs(b)?(l=b,e=g/4):e=g/(2*Math.PI)*Math.asin(b/l);return l*Math.pow(2,-10*a)*Math.sin(2*(a*d-e)*Math.PI/g)+b+c},easeInOutElastic:function(e,a,c,b,d){e=1.70158;var g=0,l=b;if(0==a)return c;if(2==(a/=d/2))return c+b;g||(g=.3*d*1.5);l<Math.abs(b)?(l=b,e=g/4):e=g/(2*Math.PI)*Math.asin(b/l);return 1>a?-.5*l*Math.pow(2,10*--a)*Math.sin(2*(a*d-e)*Math.PI/g)+c:l*Math.pow(2,-10*--a)*Math.sin(2*(a*d-e)*Math.PI/g)*.5+b+c},easeInBack:function(e,a,c,b,d,g){void 0==g&&(g=1.70158);
return b*(a/=d)*a*((g+1)*a-g)+c},easeOutBack:function(e,a,c,b,d,g){void 0==g&&(g=1.70158);return b*((a=a/d-1)*a*((g+1)*a+g)+1)+c},easeInOutBack:function(e,a,c,b,d,g){void 0==g&&(g=1.70158);return 1>(a/=d/2)?b/2*a*a*(((g*=1.525)+1)*a-g)+c:b/2*((a-=2)*a*(((g*=1.525)+1)*a+g)+2)+c},easeInBounce:function(e,a,c,b,d){return b-jQuery.easing.easeOutBounce(e,d-a,0,b,d)+c},easeOutBounce:function(e,a,c,b,d){return(a/=d)<1/2.75?7.5625*b*a*a+c:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+.75)+c:a<2.5/2.75?b*(7.5625*(a-=
2.25/2.75)*a+.9375)+c:b*(7.5625*(a-=2.625/2.75)*a+.984375)+c},easeInOutBounce:function(e,a,c,b,d){return a<d/2?.5*jQuery.easing.easeInBounce(e,2*a,0,b,d)+c:.5*jQuery.easing.easeOutBounce(e,2*a-d,0,b,d)+.5*b+c}});
(function(e,a){e.fn.imagesLoaded=function(c){function b(){var a=e(y),b=e(u);p&&(u.length?p.reject(n,a,b):p.resolve(n));e.isFunction(c)&&c.call(l,n,a,b)}function d(a){g(a.target,"error"===a.type)}function g(a,c){"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=="!==a.src&&-1===e.inArray(a,r)&&(r.push(a),c?u.push(a):y.push(a),e.data(a,"imagesLoaded",{isBroken:c,src:a.src}),v&&p.notifyWith(e(a),[c,n,e(y),e(u)]),n.length===r.length&&(setTimeout(b),n.unbind(".imagesLoaded",d)))}var l=
this,p=e.isFunction(e.Deferred)?e.Deferred():0,v=e.isFunction(p.notify),n=l.find("img").add(l.filter("img")),r=[],y=[],u=[];e.isPlainObject(c)&&e.each(c,function(a,b){if("callback"===a)c=b;else if(p)p[a](b)});n.length?n.bind("load.imagesLoaded error.imagesLoaded",d).each(function(b,c){var d=c.src,l=e.data(c,"imagesLoaded");if(l&&l.src===d)g(c,l.isBroken);else if(c.complete&&c.naturalWidth!==a)g(c,0===c.naturalWidth||0===c.naturalHeight);else if(c.readyState||c.complete)c.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==",
c.src=d}):b();return p?p.promise(l):l}})(jQuery);
$(document).ready(function(){var e=$("#slideshow_tabs .slideshow_caption"),a=new Slideshow({id:"slideshow_tabs",autoplay:!0,autoplay_start_delay:0,displayTime:3E3,easing:"swing",variableHeight:!0,variableWidth:!0,callback:function(a){e.text($("#slideshow_tabs .currentSlide figcaption").text())}});$(".slideshow .controle").click(function(){a.toggleSlideShow();$(this).toggleClass("play");$(this).toggleClass("pause")});$(".slideshow").on("mouseenter focus",function(){a.handleInMouse()}).mouseleave(function(){a.handleOutMouse()})});
(function(){TouchMouseEvent={DOWN:"touchmousedown",UP:"touchmouseup",MOVE:"touchmousemove"};var e=function(a){var b;switch(a.type){case "mousedown":b=TouchMouseEvent.DOWN;break;case "mouseup":b=TouchMouseEvent.UP;break;case "mousemove":b=TouchMouseEvent.MOVE;break;default:return}b=c(b,a,a.pageX,a.pageY);$(a.target).trigger(b)},a=function(a){var b;switch(a.type){case "touchstart":b=TouchMouseEvent.DOWN;break;case "touchend":b=TouchMouseEvent.UP;break;case "touchmove":b=TouchMouseEvent.MOVE;break;default:return}var e=
a.originalEvent.touches[0];b=b==TouchMouseEvent.UP?c(b,a,null,null):c(b,a,e.pageX,e.pageY);$(a.target).trigger(b)},c=function(a,b,c,e){return $.Event(a,{pageX:c,pageY:e,originalEvent:b})},b=$(document);"ontouchstart"in window?(b.on("touchstart",a),b.on("touchmove",a),b.on("touchend",a)):(b.on("mousedown",e),b.on("mouseup",e),b.on("mousemove",e))})();
function Slideshow(e){function a(){m.removeClass("loading");f.autoplay&&c();if(f.loop){var a=q.find(".slide").first().clone().addClass("fake post_last"),b=q.find(".slide").last().clone().addClass("fake pre_first");q.append(a).prepend(b)}p();k.div=q.find(".slide");k.count=k.div.length;m.has(".slideTabs")&&d();y();$(window).on("resize.slideshow",g);$(window).trigger("resize.slideshow")}function c(){f.loop=!0;C=window.setTimeout(function(){D=window.setInterval(function(){v("next")},f.displayTime)},f.autoplay_start_delay)}
function b(){f.autoplay&&(f.autoplay=!1,window.clearInterval(D),window.clearTimeout(C))}function d(){var a=m.find(".slideTabs");if(0===a.children().length)for(var c=f.loop?k.count-2:k.count/f.visibleSlidesCount,d=0;d<c;d++)a.append('<a href="#"></a>');a.on("click","a",function(a){a.preventDefault();b();h=1<f.visibleSlidesCount?$(this).index()*f.visibleSlidesCount+1:$(this).index()+1;r(f.loop?h:h-1)})}function g(a){w.width=m.width();f.multiple_slides?1<f.visibleSlidesCount&&k.div.width(l()):k.div.width(w.width);
n();r(f.loop?h:h-1,0);f.variableHeight&&u()}function l(){var a=f.visibleSlidesCount,b=m.find(".wrapper").width(),a=parseInt((100-(a-1)*f.slide_margin_right)/a*b/100),b=parseInt(b*f.slide_margin_right/100);m.find(".slide").width(a).css("margin-right",b);return a}function p(){m.on("click",".prev, .next",function(a){a.preventDefault();$(this).hasClass("disabled")||(b(),a=$(this).hasClass("next")?"next":"previous",v(a))})}function v(a){var b=f.visibleSlidesCount;"next"==a?f.loop?h<k.count-1?h++:(q.css({left:-k.div.eq(1).position().left}),
h=2):h<k.count&&(h+=b):f.loop?0<h?h--:(q.css({left:-k.div.eq(k.count-2).position().left}),h=k.count-3):h>b&&(h-=b);r(f.loop?h:h-1)}function n(){var a=0,b=parseInt(k.div.css("margin-right"))||0;q.width(5E4);for(var c=0;c<k.count;c++)k.div.eq(c).css("left",a+"px"),z=a=a+k.div.eq(c).outerWidth()+b;q.width(z)}function r(a,b){var c=void 0===b?f.transition_delay:b,d=k.div.eq(a),e=d.position().left,g=d.position().left+d.width()/2,h=w.width/2;f.multiple_slides&&"center"===f.align&&(e=g>h?g<z-h?e-(w.width-
d.width())/2:z-w.width:0);B();k.div.removeClass("currentSlide");d.addClass("currentSlide");q.stop(!0,!1).animate({left:-e},c,f.easing,function(){f.variableHeight&&0==E&&u();f.callback&&f.callback(w)})}function y(){var a,c,d=k.div;d.bind(TouchMouseEvent.DOWN,function(b){b.preventDefault();c=a=b.pageX});d.bind(TouchMouseEvent.MOVE,function(a){a.preventDefault();c=a.pageX});d.bind(TouchMouseEvent.UP,function(e){e.preventDefault();e=d.index($(this));f.autoplay&&b();c<a?x.hasClass("disabled")||v("next"):
c>a?t.hasClass("disabled")||v("previous"):"thumb_nails"===f.mode&&e!=h&&(h=e,n())})}function u(){$(s+" .wrapper").css("height",A());f.align_buttons()}function A(){var a=f.loop?h:h-1;return 1===f.visibleSlidesCount?$(s+" .slide").eq(a).outerHeight():function(){var a=0;m.find(".slide").each(function(){var b=$(this).outerHeight();b>a&&(a=b)});return E=a}()}function B(){0==k.count&&(h=0);h==k.count-1&&f.loop?$(s+" .slideNumber").text("1"):0==h&&f.loop?$(s+" .slideNumber").text(k.count-2):$(s+" .slideNumber").text(h);
if(m.has(".slideTabs")){var a=$(s+" .slideTabs a");a.removeClass("selected");f.loop?h==k.count-1?a.eq(0).addClass("selected"):0==h?a.eq(k.count-3).addClass("selected"):a.eq(h-1).addClass("selected"):a.eq(Math.ceil(h/f.visibleSlidesCount)-1).addClass("selected")}f.loop||(1==f.visibleSlidesCount?h==k.count&&1==h?(t.addClass("disabled"),x.addClass("disabled")):h==k.count?(t.removeClass("disabled"),x.addClass("disabled")):(1==h?t.addClass("disabled"):t.removeClass("disabled"),x.removeClass("disabled")):
h>k.count-f.visibleSlidesCount?(t.removeClass("disabled"),x.addClass("disabled")):(h<f.visibleSlidesCount?t.addClass("disabled"):t.removeClass("disabled"),x.removeClass("disabled")));$(s+" .slidesCount").text(f.loop?k.count-2:k.count)}var f=$.extend(!0,{align:"left",mode:"default",autoplay:!1,autoplay_start_delay:0,callback:null,displayTime:3E3,easing:jQuery.easing.easeInCirc,id:null,startingSlideNumber:1,visibleSlidesCount:1,slideTab_has_value:!1,transition_delay:500,preload_images:!0,loop:!0,variableHeight:!1,
variableWidth:!1,role:"",loader_image:"img/loader.gif",multiple_slides:!1,slide_margin_right:0,align_buttons:function(){var a=m.find(".next").height();m.find(".prev, .next").css("top",(A()-a)/2)}},e),w=this,s="#"+f.id,m=$(s),t=m.find(".prev"),x=m.find(".next"),q=m.find(".slides"),h=f.startingSlideNumber,D,C,k={},z=0,E=0;this.width=0;this.slideNumber=function(a){if(a)h=parseInt(a),k.div=$(s+" .slide"),k.count=k.div.length,n(),h>k.count&&0!=k.count&&(h=k.count,r(h)),B(),r(h-1);else return h};this.getSlideCount=
function(){return k.count};this.toggleSlideShow=function(){f.autoplay?(b(),f.autoplay=!1):(c(),f.autoplay=!0)};this.stopSlide=function(){f.autoplay&&(b(),f.autoplay=!1)};this.runSlide=function(){f.autoplay||(c(),f.autoplay=!0)};this.handleInMouse=function(){$(".controle").hasClass("pause")&&($(".controle").removeClass("pause"),$(".controle").addClass("play"),this.stopSlide())};this.handleOutMouse=function(){$(".controle").hasClass("play")&&($(".controle").removeClass("play"),$(".controle").addClass("pause"),
this.runSlide())};m.addClass("loading");q.find("img").length&&f.preload_images?"function"!==typeof jQuery.fn.imagesLoaded?a():q.imagesLoaded(a):a()};